<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="wall_length" value="1"/>
    <xacro:property name="wall_height" value="1.5"/>
    <xacro:property name="top_length" value="1"/>
    <xacro:property name="top_height" value="1"/>
    <xacro:property name="wall_thickness" value="0.045"/>
    <xacro:property name="chassis_mass" value="1.0"/>
    <xacro:property name="arm_offset" value="0.5"/>



    <material name="white">
        <color rgba="1 1 1 0.5" />
    </material>

    <material name="orange">
        <color rgba="1 0.3 0.1 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 0.5"/>
    </material>

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>

    <!-- BASE LINK -->

    <link name="base_link">
    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>

    <link name="base_footprint">
    </link>


    <!-- KIOSK LINK -->

    <joint name="kiosk_joint" type="fixed">
        <parent link="base_link"/>
        <child link="kiosk"/>
        <origin xyz="${-arm_offset} 0 ${-wall_thickness}"/>
    </joint>

    <link name="kiosk">
        <visual>
            <!-- Back wall -->
            <origin xyz="${wall_thickness/2} 0 ${wall_height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${wall_length} ${wall_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <visual>
            <!-- Front wall -->
            <origin xyz="${wall_length - wall_thickness/2} 0 ${wall_height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${wall_length} ${wall_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <visual>
            <!-- Left wall -->
            <origin xyz="${wall_length/2} ${wall_length/2 - wall_thickness/2} ${wall_height/2}"/>
            <geometry>
                <box size="${wall_length - 2*wall_thickness} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <visual>
            <!-- Right wall -->
            <origin xyz="${wall_length/2} ${-wall_length/2 + wall_thickness/2} ${wall_height/2}"/>
            <geometry>
                <box size="${wall_length - 2*wall_thickness} ${wall_thickness} ${wall_height}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <!-- Top wall -->
        <visual>
            <origin xyz="${wall_length/2} 0 ${wall_height - wall_thickness/2}"/>
            <geometry>
                <box size="${top_length} ${top_height} ${wall_thickness}"/>
            </geometry>
        </visual>
        <!-- Back wall -->
        <collision>
            <origin xyz="${wall_thickness/2} 0 ${wall_height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${wall_length} ${wall_height}"/>
            </geometry>
        </collision>
        <!-- Front wall -->
        <collision>
            <origin xyz="${wall_length - wall_thickness/2} 0 ${wall_height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${wall_length} ${wall_height}"/>
            </geometry>
        </collision>
        <!-- Left wall -->
        <collision>
            <origin xyz="${wall_length/2} ${wall_length/2 - wall_thickness/2} ${wall_height/2}"/>
            <geometry>
                <box size="${wall_length - 2*wall_thickness} ${wall_thickness} ${wall_height}"/>
            </geometry>
        </collision>
        <!-- Right wall -->
        <collision>
            <origin xyz="${wall_length/2} ${-wall_length/2 + wall_thickness/2} ${wall_height/2}"/>
            <geometry>
                <box size="${wall_length - 2*wall_thickness} ${wall_thickness} ${wall_height}"/>
            </geometry>
        </collision>
        <!-- Top wall -->
        <collision>
            <origin xyz="${wall_length/2} 0 ${wall_height - wall_thickness/2}"/>
            <geometry>
                <box size="${top_length} ${top_height} ${wall_thickness}"/>
            </geometry>
        </collision>
        <xacro:inertial_box mass="10" x="${wall_length}" y="${wall_length}" z="${wall_height}">
            <origin xyz="${wall_length/2} 0 ${wall_height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="kiosk">
        <material>Gazebo/GreyTransparent</material>
    </gazebo>

</robot>
