<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="inertial_macros.xacro"/>


    <xacro:property name="width" value="1.215"/>
    <xacro:property name="length" value="1.260"/>
    <xacro:property name="height" value="1.170"/>

    <xacro:property name="wall_thickness" value="0.045"/>
    <xacro:property name="arm_offset" value="0.4"/>

    <material name="white">
        <color rgba="1 1 1 0.5" />
    </material>


    <!-- BASE LINK -->
    <link name="base_link">
    </link>


    <!-- KIOSK LINK -->

    <joint name="kiosk_joint" type="fixed">
        <parent link="base_link"/>
        <child link="kiosk"/>
        <origin xyz="${-arm_offset} 0 0"/>
    </joint>

    <link name="kiosk">
        <!-- Back wall -->
        <visual>
            <origin xyz="${wall_thickness/2} 0 ${height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${wall_thickness/2} 0 ${height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${width} ${height}"/>
            </geometry>
        </collision>
         <!-- Front wall -->
        <visual>
            <origin xyz="${length - wall_thickness/2} 0 ${height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${length - wall_thickness/2} 0 ${height/2}"/>
            <geometry>
                <box size="${wall_thickness} ${width} ${height}"/>
            </geometry>
        </collision>
        <!-- Left wall -->
        <visual>
            <origin xyz="${length/2} ${width/2 - wall_thickness/2} ${height/2}"/>
            <geometry>
                <box size="${length - 2 * wall_thickness} ${wall_thickness} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${length/2} ${width/2 - wall_thickness/2} ${height/2}"/>
            <geometry>
                <box size="${length - 2 * wall_thickness} ${wall_thickness} ${height}"/>
            </geometry>
        </collision>
        <!-- Right wall -->
        <visual>
            <origin xyz="${length/2} ${-width/2 + wall_thickness/2} ${height/2}"/>
            <geometry>
                <box size="${length - 2*wall_thickness} ${wall_thickness} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${length/2} ${-width/2 + wall_thickness/2} ${height/2}"/>
            <geometry>
                <box size="${length - 2*wall_thickness} ${wall_thickness} ${height}"/>
            </geometry>
        </collision>
        <!-- Top wall -->
        <visual>
            <origin xyz="${length/2} 0 ${height - wall_thickness/2}"/>
            <geometry>
                <box size="${length} ${width} ${wall_thickness}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <!-- <collision>
            <origin xyz="${length/2} 0 ${height - wall_thickness/2}"/>
            <geometry>
                <box size="${length} ${width} ${wall_thickness}"/>
            </geometry>
        </collision> -->

        <xacro:inertial_box mass="10" x="${length}" y="${width}" z="${height}">
            <origin xyz="${length/2} 0 ${height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <gazebo reference="kiosk">
        <material>Gazebo/GreyTransparent</material>
    </gazebo>

</robot>
